# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(478, 415)
        self.gridLayout = QtWidgets.QGridLayout(SettingsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyButton = QtWidgets.QPushButton(parent=SettingsWindow)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.closeButton = QtWidgets.QPushButton(parent=SettingsWindow)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=SettingsWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.generalTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showOutputTableCheckBox = QtWidgets.QCheckBox(parent=self.generalTab)
        self.showOutputTableCheckBox.setObjectName("showOutputTableCheckBox")
        self.gridLayout_2.addWidget(self.showOutputTableCheckBox, 2, 0, 1, 1)
        self.hideSuccessCheckBox = QtWidgets.QCheckBox(parent=self.generalTab)
        self.hideSuccessCheckBox.setObjectName("hideSuccessCheckBox")
        self.gridLayout_2.addWidget(self.hideSuccessCheckBox, 3, 0, 1, 1)
        self.experimentalFeaturesCheckBox = QtWidgets.QCheckBox(parent=self.generalTab)
        self.experimentalFeaturesCheckBox.setObjectName("experimentalFeaturesCheckBox")
        self.gridLayout_2.addWidget(self.experimentalFeaturesCheckBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.generalTab, "")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.infoTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(parent=self.infoTab)
        self.infoLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.infoLabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.infoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.infoLabel.setOpenExternalLinks(True)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.tabWidget.addTab(self.infoTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(SettingsWindow)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(SettingsWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Form"))
        self.applyButton.setText(_translate("SettingsWindow", " Apply "))
        self.closeButton.setText(_translate("SettingsWindow", " Close "))
        self.showOutputTableCheckBox.setText(_translate("SettingsWindow", "Automatically show Output Table after Execution"))
        self.hideSuccessCheckBox.setText(_translate("SettingsWindow", "Hide Success Dialog"))
        self.experimentalFeaturesCheckBox.setText(_translate("SettingsWindow", "Enable Experimental Features"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("SettingsWindow", "General"))
        self.infoLabel.setText(_translate("SettingsWindow", "<html><head/><body><p><span style=\" font-weight:700;\">SQL Query Tool for Excel</span></p><p>Version: 2.0.0</p><p>Developed by Manyullyn17<br/></p><p>A lightweight tool for running SQL queries on Excel files.<br/></p><p><a href=\"https://github.com/Manyullyn17/Excel_SQL_GUI\"><span style=\" text-decoration: underline; color:#007af4;\">GitHub Repo</span></a><br/></p><p><span style=\" font-style:italic;\">Powered by Python, PyQt6, Pandas, openpyxl, and SQLite.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("SettingsWindow", "Info"))
